name: event_sphere
description: A centralized academic event discovery and certification platform.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5
  firebase_data_connect: any
  firebase_app_check: ^0.4.1+3


  # State Management
  provider: ^6.1.2
  shared_preferences: ^2.2.2


  # UI & Utilities
  intl: ^0.20.2
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.6
  url_launcher: ^6.3.1
  image_picker: ^1.0.7

  # PDF Viewer (for certificates)
  syncfusion_flutter_pdfviewer: ^32.1.21
  google_fonts: ^7.0.2
  share_plus: ^12.0.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.4
  cloudinary_public: ^0.23.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #       - asset: assets/fonts/Inter-Bold.ttf
